services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.26.2
    - PORT=4000
    - DB_DIALECT=postgresql
    - DB_HOST=db
    - secure: ayatQ03JxfK/Do3FiZ7ePoWujhiB6iIMw0XKuhbXr65vy0MS7am2sSNvwPpxYrZXrq99acYyWdunWbz/dxQztgwZyFVhNWcZOVxmocSonshixwpmFWnD42KjxghMLAJUU4IGlZBVaab1D7Z7XCmYwcmMQHcYNA4gbAOEcJIlnm2AUQz3onBtGPof9t33AOnQt6bsmVH1e9tQroh3wnde34/Fxx0Y5WxQ2YrxOvRPhkp9UVqskQ2wZa8FBSzXv31ND9VLaAfFyuWGXiolcernKUimekP2GtbxdBSCGZIgSoxFRD6yVNcVoz8MasMqmGzrIN4LqyODEeZBaIvX5TyyEKeSveYK/RdSe41k/vBF7lJvQ5nH7uB/k9X46jIMqQvCjm9Bt7wvyETCiIVpCznwWVUT8x8f4NRl7VTWmArd5xHMaG6VSJgjRAKHASrMthr/1AWn4q8W8Lp2BWlsSvx7F7dv14QNzqKmmxGuUv8L+RmC5p6PxBFj2ZBFMFO5Bdv5rOOLclhwrqEl2kuFqwejd24bq57ZGULm36dLn9VcfOtip4gdM8bnE9T6z5IgiQodVdQZ+nT782HUyD3qI+Wa2q6dA/7RQaTU3yQyz4A2XOs6MMS/KDKSk1gtyZ0iU7Y6PsUoX+jDdleYmOeXIe/nyx/PyXBlk7srRGg6Z3E3H84=
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
    -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - docker-compose up -d --build
scripts:
  - docker-compose exec app yarn test
after_script:
  - docker-compose down
