language: node_js
node_js:
  - 12
deploy:
  api_key:
    secure: tLAJOZnw3EYor7SKfDm6+q8b+xXxxE1A0JLB01DJgARFzMo+7Gu0GtxzWMDgxV5SsrY7drV1OWla1ZBwxQgNiW4lzU9EjsypQ6cPQUyx1q/kvhPTwGh/mRXBAQ+k7fH112cylIigIsiBfKri4GLKeuQ2GhprzapZH4dVwWLXbCzIDDYe2kcWA1VKDvg4HttNEdWLQUuKHM/g7SwAfpwIrPvNYKtDDCpp7BotadfvU4mKTOTpS4mf+WRWDYs+iy7KnJwQzE4p5hBz6+7QTocQO36BiqqlBJfcFPz8pSp0x1riePabQNU5x1+6Y4lpdcXpwDSXA3XIpRYn8OvyB8vmRdtqMz0BCnqQzuflS7gkDiYQ5uWqxNuh49KmLaJvEtVVvEuz4u0yUaaKQ+kBXYCgOUNI0RiXdrDYOCB9N1lo9gA0CGVYVQJd61WHAJ1mkztGpZ66l+Kd+ejXOcN4X2i/hqUdGGsnN0JqjKgvrO/04594vT5yKrDMDaoPseH1klSMwhuSZR/2QNySJ32MzUE9Hdosx0ZOuYCeC+jAqjt6fZrlUWHvg557bE1LgusSk5wmg3Wxa0e5fkHZgbUNP79i4G+RnNjwjzVJUqddukok5RZPFFRrYzWlNdABOK56f4OlfZL7UmQimTpy09hxA6OT8nZLRI72afT7IqRyUtr5XW0=
  app: lfoliveira-social-api
  run: 'yarn knex migrate:latest'
