version: '3.8'

services:
  app:
    build: .
    container_name: 'social-server'
    command: sh -c "npm install && npm run migrate && npm run build && npm run start"
    ports:
      - 4000:4000
    links:
      - db
    depends_on:
      - db
    environment:
      NODE_ENV: production
      SECRET: ${SECRET}
      PORT: ${PORT}
      DB_DIALECT: postgresql
      DB_HOST: db
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_NAME_TEST: ${DB_NAME_TEST}
  db:
    image: postgres:13
    container_name: 'social-db'
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DB_NAME},${DB_NAME_TEST}
